spring:
  datasource:
    url: "jdbc:mysql://${MYSQL_DB_HOST:localhost}:${MYSQL_DB_PORT:3306}/${MYSQL_DB_SID:userCatalog}?allowPublicKeyRetrieval=true&useSSL=false"
    username: "${MYSQL_DB_USERNAME}"
    password: "${MYSQL_DB_PASSWORD}"
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  sql:
    init:
      mode: never #using liquibase to initialize db

