spring:
  datasource:
    url: "jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_SID:twitter}?allowPublicKeyRetrieval=true&useSSL=false"
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  sql:
    init:
      mode: never #using liquibase to initialize db

liquibase:
  change-log: classpath:db/changelog/db.changelog-master.yaml
  enabled: true
  drop-first: true
  default-schema: twitter
  default-catalog: twitter
  contexts: dev
  

logging:
  level:
    liquibase: WARN

